name: Debug CI

on:
  workflow_dispatch:

jobs:
  build:
    name: Debug Workflows

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    steps:
      - name: Install system dependencies (Linux)
        run: sudo apt update && sudo apt-get install libev-dev libonig-dev libcurl4-openssl-dev
        if: runner.os == 'Linux'

      - name: Install system dependencies (macOS)
        run: brew install libev openssl@3 # Openssl is a workaround for https://github.com/ocaml/opam-repository/issues/19676
        if: runner.os == 'macOS'
